import { lazy } from 'react'

export const GeneratePage = lazy(() => import('./GeneratePage'))
export const BatchPage = lazy(() => import('./BatchPage'))
export const ComparePage = lazy(() => import('./ComparePage'))
export const HistoryPage = lazy(() => import('./HistoryPage'))
export const UnderstandPage = lazy(() => import('./UnderstandPage'))
export const SettingsPage = lazy(() => import('./SettingsPage'))
export const DirectorPage = lazy(() => import('./DirectorPage'))
export const PromptTemplatesPage = lazy(() => import('./PromptTemplatesPage'))
export const StoryboardSplitPage = lazy(() => import('./StoryboardSplitPage'))
export const SmartErasePage = lazy(() => import('./SmartErasePage'))
export const PortraitLibraryPage = lazy(() => import('./PortraitLibraryPage'))
export const AgentWorkspacePage = lazy(() => import('./AgentWorkspacePage'))
export const MarketplacePage = lazy(() => import('./MarketplacePage'))
